FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Car Pool

Car Pool is an API for a car pooling webapp for Practo Employees

## Listings Collection [/listing/{id_listing}]

### List any one Listing [GET]

+ Parameters
    + id_listing:`1` (number,optional) - ID of the Listing in the form of an integer

+ Response 200 (application/json)

        [
            {   
                "id": 1,
                "availability": 1,
                "departTime": 1472208258000,
                "seatAvailable": 4,
                  "addressModel": {
                    "id": 2,
                    "latitude": 12.5818,
                    "longitude": 77.3537,
                    "destination": "JP Nagar"
                  },
                 "sourceModel": {
                    "id": 2,
                    "address": "Goplan Mall",
                    "nameOffice": "Practo Venus"
                  },
                  "userModel": {
                    "id": 3,
                    "email": "ankit.singh12@practo.com",
                    "mobile": "9912381899",
                    "name": "Ankit214"
                 },
                 "vehicleModel": {
                     "id": 3,
                     "capacity": 4,
                     "model": "Honda",
                     "numberPlate": "UP16F8598",
                     "userModel": {
                          "id": 2,
                          "email": "prashant.baisla@practo.com",
                          "mobile": "9912381798",
                          "name": "Prashant"
                    }
                }
            }
        ]

### Create a New Listing [POST]

+ Request (application/json)

        {
            "userModel":{
                "id":1
            },
            "addressModel":{
                "id":2
            },
            "depart_time":"201608250730",
            "seatAvailable": 3,
            "sourceModel":{
                "id":2
            },
            "vehicleModel":{
                "id":3,
                "userModel":{
                    "id":1
                }
            }
        }


+ Response 201 (application/json)

    + Headers
    
            Location: /listing/1

    + Body
        
            {
                "id": 12,
                "availability": 1,
                "departTime": 1472314833000,
                "seatAvailable": 2,
                "addressModel": {
                    "id": 3,
                    "latitude": 14.58,
                    "longitude": 87.3537,
                    "destination": "Bannerghata Road"
                },
                "sourceModel": {
                    "id": 2,
                    "address": "Practo Goplan",
                    "nameOffice": "Practo Venus"
               },
              "userModel": {
                  "id": 4,
                    "email": "poorna@practo.com",
                    "mobile": "9912381801",
                    "name": "Poorna"
              },
              "vehicleModel": {
                "id": 3,
                "capacity": 4,
                "model": "Honda",
                "numberPlate": "UP16F8598",
                "userModel": {
                  "id": 2,
                  "email": "prashant.baisla@practo.com",
                  "mobile": "9912381798",
                  "name": "Prashant"
                }
              }
            }


### Update a Listing [PUT]

+ Parameters
    + id_listing (number) - ID of the Listing in the form of an integer

+ Request (application/json)

        {
            "userModel":{
                "id":2
            },
            "addressModel":{
                "id":2
            },
            "departTime":"201608250730",
            "seatAvailable": 3,
            "sourceModel":{
                "id":2
            },
            "vehicleModel":{
                "id":3,
                "userModel":{
                    "id":1
                }
            }
        }

+ Response 200 (application/json)

    + Headers

            Location: /listing/2

 + Body

            {
                "id": 12,
                "availability": 1,
                "departTime": 1472314833000,
                "seatAvailable": 2,
                "addressModel": {
                    "id": 3,
                    "latitude": 14.58,
                    "longitude": 87.3537,
                    "destination": "Bannerghata Road"
                },
                "sourceModel": {
                    "id": 2,
                    "address": "Practo Goplan",
                    "nameOffice": "Practo Venus"
               },
              "userModel": {
                  "id": 2,
                    "email": "poorna@practo.com",
                    "mobile": "9912381801",
                    "name": "Poorna"
              },
              "vehicleModel": {
                "id": 3,
                "capacity": 4,
                "model": "Honda",
                "numberPlate": "UP16F8598",
                "userModel": {
                  "id": 2,
                  "email": "prashant.baisla@practo.com",
                  "mobile": "9912381798",
                  "name": "Prashant"
                }
              }
            }

### Delete a listing [DELETE]

+ Response 204

    + Headers
    
            Location: /listing/1