-- MySQL Script generated by MySQL Workbench
-- Thu Aug 25 17:05:16 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema car_pool
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema car_pool
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `car_pool` DEFAULT CHARACTER SET utf8 ;
USE `car_pool` ;

-- -----------------------------------------------------
-- Table `car_pool`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_pool`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `email` VARCHAR(200) NOT NULL,
  `mobile` VARCHAR(10) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idUsers_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`vehicle`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_pool`.`vehicle` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `capacity` INT NOT NULL,
  `id_owner` INT NOT NULL,
  `number_plate` VARCHAR(45) NOT NULL,
  `model` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `idOwner_idx` (`id_owner` ASC),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  CONSTRAINT `idOwner`
    FOREIGN KEY (`id_owner`)
    REFERENCES `car_pool`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`source`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_pool`.`source` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(200) NOT NULL,
  `nameOffice` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_pool`.`address` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `latitude` DECIMAL(10,8) NOT NULL,
  `longitude` DECIMAL(11,8) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`listing`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_pool`.`listing` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_lister` INT NOT NULL,
  `id_vehicle` INT NOT NULL,
  `depart_time` TIMESTAMP NOT NULL,
  `id_source` INT NOT NULL,
  `availability` TINYINT(1) NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  `seat_available` INT NOT NULL,
  `id_destination` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idListings_UNIQUE` (`id` ASC),
  INDEX `idLister_idx` (`id_lister` ASC),
  INDEX `idCar_idx` (`id_vehicle` ASC),
  INDEX `idSource_idx` (`id_source` ASC),
  INDEX `idDestination_idx` (`id_destination` ASC),
  CONSTRAINT `idLister`
    FOREIGN KEY (`id_lister`)
    REFERENCES `car_pool`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idCar`
    FOREIGN KEY (`id_vehicle`)
    REFERENCES `car_pool`.`vehicle` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idSource`
    FOREIGN KEY (`id_source`)
    REFERENCES `car_pool`.`source` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idDestination`
    FOREIGN KEY (`id_destination`)
    REFERENCES `car_pool`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `car_pool`.`booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `car_pool`.`booking` (
  `idBooking` INT NOT NULL AUTO_INCREMENT,
  `idBooker` INT NOT NULL,
  `idListing` INT NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `modified_at` DATETIME NULL,
  `deleted_at` DATETIME NULL,
  PRIMARY KEY (`idBooking`),
  INDEX `idBooker_idx` (`idBooker` ASC),
  INDEX `idListing_idx` (`idListing` ASC),
  UNIQUE INDEX `idBooking_UNIQUE` (`idBooking` ASC),
  CONSTRAINT `idBooker`
    FOREIGN KEY (`idBooker`)
    REFERENCES `car_pool`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idListing`
    FOREIGN KEY (`idListing`)
    REFERENCES `car_pool`.`listing` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
